import type { Legend } from "./types";

/**
 * The seed roster. Ratings are an opinionated, for-the-culture take — a game,
 * not a ledger. Dead legends (the David Senra / "Founders" canon) render as
 * ICONs; living legends are pulled from the Forbes-tier of tech & business.
 *
 * Note the dark-talent thesis hiding in the dead icons: Ramanujan, Tesla, and
 * Turing carry sky-high INO/VIS but low CAP — genius the market underpriced.
 * That gap is the whole reason this platform exists.
 */
export const LEGENDS: Legend[] = [
  // ───────────── DEAD LEGENDS · ICONS ─────────────
  {
    id: "rockefeller",
    name: "John D. Rockefeller",
    surname: "Rockefeller",
    role: "Industrialist",
    status: "dead",
    domain: "Industry",
    company: "Standard Oil",
    era: "1839-1937",
    blurb: "Defined the modern monopoly.",
    stats: { vis: 95, exe: 99, inf: 96, ino: 82, cap: 99, grt: 97 },
  },
  {
    id: "carnegie",
    name: "Andrew Carnegie",
    surname: "Carnegie",
    role: "Industrialist",
    status: "dead",
    domain: "Industry",
    company: "Carnegie Steel",
    era: "1835-1919",
    blurb: "Steel king who gave it all away.",
    stats: { vis: 92, exe: 96, inf: 90, ino: 80, cap: 97, grt: 95 },
  },
  {
    id: "ford",
    name: "Henry Ford",
    surname: "Ford",
    role: "Industrialist",
    status: "dead",
    domain: "Industry",
    company: "Ford Motor",
    era: "1863-1947",
    blurb: "Put the world on wheels.",
    stats: { vis: 96, exe: 94, inf: 93, ino: 97, cap: 92, grt: 90 },
  },
  {
    id: "vanderbilt",
    name: "Cornelius Vanderbilt",
    surname: "Vanderbilt",
    role: "Industrialist",
    status: "dead",
    domain: "Industry",
    company: "Railroads",
    era: "1794-1877",
    blurb: "Railroads and ruthless ambition.",
    stats: { vis: 88, exe: 96, inf: 85, ino: 78, cap: 95, grt: 98 },
  },
  {
    id: "jobs",
    name: "Steve Jobs",
    surname: "Jobs",
    role: "Visionary",
    status: "dead",
    domain: "Tech",
    company: "Apple",
    era: "1955-2011",
    blurb: "Made computers feel like magic.",
    stats: { vis: 99, exe: 94, inf: 98, ino: 97, cap: 93, grt: 92 },
  },
  {
    id: "edison",
    name: "Thomas Edison",
    surname: "Edison",
    role: "Inventor",
    status: "dead",
    domain: "Science",
    company: "General Electric",
    era: "1847-1931",
    blurb: "1,093 patents. The idea factory.",
    stats: { vis: 93, exe: 92, inf: 88, ino: 99, cap: 85, grt: 96 },
  },
  {
    id: "tesla",
    name: "Nikola Tesla",
    surname: "Tesla",
    role: "Inventor",
    status: "dead",
    domain: "Science",
    company: "AC Power",
    era: "1856-1943",
    blurb: "Genius the market never paid.",
    stats: { vis: 99, exe: 74, inf: 80, ino: 99, cap: 40, grt: 95 },
  },
  {
    id: "disney",
    name: "Walt Disney",
    surname: "Disney",
    role: "Founder",
    status: "dead",
    domain: "Creative",
    company: "Disney",
    era: "1901-1966",
    blurb: "Built an empire on imagination.",
    stats: { vis: 98, exe: 90, inf: 95, ino: 94, cap: 80, grt: 93 },
  },
  {
    id: "walton",
    name: "Sam Walton",
    surname: "Walton",
    role: "Operator",
    status: "dead",
    domain: "Business",
    company: "Walmart",
    era: "1918-1992",
    blurb: "Everyday low prices, relentless ops.",
    stats: { vis: 90, exe: 98, inf: 86, ino: 82, cap: 96, grt: 94 },
  },
  {
    id: "kroc",
    name: "Ray Kroc",
    surname: "Kroc",
    role: "Operator",
    status: "dead",
    domain: "Business",
    company: "McDonald's",
    era: "1902-1984",
    blurb: "Scaled a burger into a system.",
    stats: { vis: 84, exe: 97, inf: 85, ino: 80, cap: 90, grt: 96 },
  },
  {
    id: "lauder",
    name: "Estee Lauder",
    surname: "Lauder",
    role: "Founder",
    status: "dead",
    domain: "Business",
    company: "Estee Lauder",
    era: "1908-2004",
    blurb: "Door-to-door samples to an empire.",
    stats: { vis: 90, exe: 93, inf: 92, ino: 85, cap: 88, grt: 95 },
  },
  {
    id: "chanel",
    name: "Coco Chanel",
    surname: "Chanel",
    role: "Founder",
    status: "dead",
    domain: "Creative",
    company: "Chanel",
    era: "1883-1971",
    blurb: "Liberated how the world dresses.",
    stats: { vis: 96, exe: 88, inf: 95, ino: 94, cap: 82, grt: 93 },
  },
  {
    id: "jpmorgan",
    name: "J.P. Morgan",
    surname: "Morgan",
    role: "Financier",
    status: "dead",
    domain: "Finance",
    company: "J.P. Morgan",
    era: "1837-1913",
    blurb: "Bailed out the U.S. Treasury himself.",
    stats: { vis: 90, exe: 94, inf: 98, ino: 75, cap: 99, grt: 88 },
  },
  {
    id: "hughes",
    name: "Howard Hughes",
    surname: "Hughes",
    role: "Visionary",
    status: "dead",
    domain: "Business",
    company: "Hughes Aircraft",
    era: "1905-1976",
    blurb: "Aviator, mogul, obsessive visionary.",
    stats: { vis: 95, exe: 82, inf: 84, ino: 92, cap: 90, grt: 80 },
  },
  {
    id: "morita",
    name: "Akio Morita",
    surname: "Morita",
    role: "Founder",
    status: "dead",
    domain: "Tech",
    company: "Sony",
    era: "1921-1999",
    blurb: "Made Sony a global byword.",
    stats: { vis: 94, exe: 92, inf: 88, ino: 93, cap: 86, grt: 90 },
  },
  {
    id: "honda",
    name: "Soichiro Honda",
    surname: "Honda",
    role: "Inventor",
    status: "dead",
    domain: "Industry",
    company: "Honda",
    era: "1906-1991",
    blurb: "From bombed-out shed to motor giant.",
    stats: { vis: 90, exe: 93, inf: 82, ino: 95, cap: 84, grt: 97 },
  },
  {
    id: "ogilvy",
    name: "David Ogilvy",
    surname: "Ogilvy",
    role: "Creative",
    status: "dead",
    domain: "Creative",
    company: "Ogilvy & Mather",
    era: "1911-1999",
    blurb: "The father of advertising.",
    stats: { vis: 92, exe: 88, inf: 94, ino: 90, cap: 78, grt: 85 },
  },
  {
    id: "ramanujan",
    name: "Srinivasa Ramanujan",
    surname: "Ramanujan",
    role: "Scientist",
    status: "dead",
    domain: "Science",
    company: "Number Theory",
    era: "1887-1920",
    blurb: "No training. The notebook of a century.",
    stats: { vis: 99, exe: 85, inf: 80, ino: 99, cap: 20, grt: 99 },
  },
  {
    id: "turing",
    name: "Alan Turing",
    surname: "Turing",
    role: "Scientist",
    status: "dead",
    domain: "Science",
    company: "Computation",
    era: "1912-1954",
    blurb: "Cracked Enigma. Invented the computer.",
    stats: { vis: 98, exe: 88, inf: 82, ino: 99, cap: 30, grt: 97 },
  },
  {
    id: "hopper",
    name: "Grace Hopper",
    surname: "Hopper",
    role: "Scientist",
    status: "dead",
    domain: "Tech",
    company: "COBOL",
    era: "1906-1992",
    blurb: "Compiled the future of software.",
    stats: { vis: 90, exe: 93, inf: 85, ino: 92, cap: 40, grt: 95 },
  },

  // ───────────── LIVING LEGENDS ─────────────
  {
    id: "musk",
    name: "Elon Musk",
    surname: "Musk",
    role: "Founder",
    status: "living",
    domain: "Tech",
    company: "Tesla / SpaceX",
    era: "b. 1971",
    blurb: "Cars, rockets, and sheer will.",
    stats: { vis: 99, exe: 96, inf: 99, ino: 97, cap: 99, grt: 95 },
  },
  {
    id: "bezos",
    name: "Jeff Bezos",
    surname: "Bezos",
    role: "Founder",
    status: "living",
    domain: "Tech",
    company: "Amazon",
    era: "b. 1964",
    blurb: "Day 1, forever. The everything store.",
    stats: { vis: 97, exe: 99, inf: 95, ino: 92, cap: 99, grt: 94 },
  },
  {
    id: "huang",
    name: "Jensen Huang",
    surname: "Huang",
    role: "Founder",
    status: "living",
    domain: "Tech",
    company: "NVIDIA",
    era: "b. 1963",
    blurb: "Bet the company on AI. Won.",
    stats: { vis: 97, exe: 97, inf: 93, ino: 96, cap: 97, grt: 95 },
  },
  {
    id: "gates",
    name: "Bill Gates",
    surname: "Gates",
    role: "Founder",
    status: "living",
    domain: "Tech",
    company: "Microsoft",
    era: "b. 1955",
    blurb: "Software on every desk.",
    stats: { vis: 95, exe: 96, inf: 96, ino: 90, cap: 98, grt: 90 },
  },
  {
    id: "buffett",
    name: "Warren Buffett",
    surname: "Buffett",
    role: "Investor",
    status: "living",
    domain: "Finance",
    company: "Berkshire Hathaway",
    era: "b. 1930",
    blurb: "The oracle. Compounding incarnate.",
    stats: { vis: 94, exe: 93, inf: 95, ino: 72, cap: 99, grt: 96 },
  },
  {
    id: "zuckerberg",
    name: "Mark Zuckerberg",
    surname: "Zuckerberg",
    role: "Founder",
    status: "living",
    domain: "Tech",
    company: "Meta",
    era: "b. 1984",
    blurb: "Wired up a third of humanity.",
    stats: { vis: 92, exe: 96, inf: 94, ino: 88, cap: 97, grt: 93 },
  },
  {
    id: "altman",
    name: "Sam Altman",
    surname: "Altman",
    role: "Founder",
    status: "living",
    domain: "Tech",
    company: "OpenAI",
    era: "b. 1985",
    blurb: "Shipped AI to the world's desktop.",
    stats: { vis: 96, exe: 92, inf: 95, ino: 93, cap: 90, grt: 90 },
  },
  {
    id: "arnault",
    name: "Bernard Arnault",
    surname: "Arnault",
    role: "Operator",
    status: "living",
    domain: "Business",
    company: "LVMH",
    era: "b. 1949",
    blurb: "Turned luxury into the largest fortune.",
    stats: { vis: 90, exe: 96, inf: 92, ino: 80, cap: 99, grt: 92 },
  },
  {
    id: "naval",
    name: "Naval Ravikant",
    surname: "Ravikant",
    role: "Investor",
    status: "living",
    domain: "Tech",
    company: "AngelList",
    era: "b. 1974",
    blurb: "Angel philosopher of leverage.",
    stats: { vis: 96, exe: 85, inf: 94, ino: 88, cap: 86, grt: 84 },
  },
  {
    id: "balaji",
    name: "Balaji Srinivasan",
    surname: "Srinivasan",
    role: "Visionary",
    status: "living",
    domain: "Tech",
    company: "The Network State",
    era: "b. 1980",
    blurb: "Architect of the network state.",
    stats: { vis: 99, exe: 84, inf: 92, ino: 95, cap: 85, grt: 88 },
  },
  {
    id: "thiel",
    name: "Peter Thiel",
    surname: "Thiel",
    role: "Investor",
    status: "living",
    domain: "Finance",
    company: "Founders Fund",
    era: "b. 1967",
    blurb: "Zero to one. Contrarian capital.",
    stats: { vis: 97, exe: 88, inf: 93, ino: 90, cap: 95, grt: 88 },
  },
  {
    id: "collison",
    name: "Patrick Collison",
    surname: "Collison",
    role: "Founder",
    status: "living",
    domain: "Tech",
    company: "Stripe",
    era: "b. 1988",
    blurb: "Made money move like email.",
    stats: { vis: 94, exe: 95, inf: 88, ino: 92, cap: 90, grt: 90 },
  },
  {
    id: "chesky",
    name: "Brian Chesky",
    surname: "Chesky",
    role: "Founder",
    status: "living",
    domain: "Tech",
    company: "Airbnb",
    era: "b. 1981",
    blurb: "Turned spare rooms into trust.",
    stats: { vis: 93, exe: 91, inf: 88, ino: 90, cap: 86, grt: 92 },
  },
  {
    id: "nadella",
    name: "Satya Nadella",
    surname: "Nadella",
    role: "Operator",
    status: "living",
    domain: "Tech",
    company: "Microsoft",
    era: "b. 1967",
    blurb: "Rebooted a giant around the cloud.",
    stats: { vis: 92, exe: 96, inf: 93, ino: 85, cap: 95, grt: 90 },
  },
  {
    id: "andreessen",
    name: "Marc Andreessen",
    surname: "Andreessen",
    role: "Investor",
    status: "living",
    domain: "Tech",
    company: "a16z",
    era: "b. 1971",
    blurb: "Wrote the browser, funds the future.",
    stats: { vis: 96, exe: 86, inf: 94, ino: 92, cap: 93, grt: 85 },
  },
  {
    id: "senra",
    name: "David Senra",
    surname: "Senra",
    role: "Creative",
    status: "living",
    domain: "Creative",
    company: "Founders Podcast",
    era: "b. 1984",
    blurb: "Studies the dead to arm the living.",
    stats: { vis: 90, exe: 92, inf: 86, ino: 80, cap: 60, grt: 97 },
  },
];

export function getLegend(id: string): Legend | undefined {
  return LEGENDS.find((l) => l.id === id);
}
